// commandindex.ts - Module for my commands index.
// Mar 24, 2021
// Chris M.
// https://github.com/RealTimeChris
'use strict';
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
var commands = new Map();
var botinfo_1 = __importDefault(require("./commands/botinfo"));
commands.set(botinfo_1.default.name, botinfo_1.default);
var deletedbentry_1 = __importDefault(require("./commands/deletedbentry"));
commands.set(deletedbentry_1.default.name, deletedbentry_1.default);
var displayguildsdata_1 = __importDefault(require("./commands/displayguildsdata"));
commands.set(displayguildsdata_1.default.name, displayguildsdata_1.default);
var ghost_1 = __importDefault(require("./commands/ghost"));
commands.set(ghost_1.default.name, ghost_1.default);
var help_1 = __importDefault(require("./commands/help"));
commands.set(help_1.default.name, help_1.default);
var jannyoptions_1 = __importDefault(require("./commands/jannyoptions"));
commands.set(jannyoptions_1.default.name, jannyoptions_1.default);
var listdbguilds_1 = __importDefault(require("./commands/listdbguilds"));
commands.set(listdbguilds_1.default.name, listdbguilds_1.default);
var managelogs_1 = __importDefault(require("./commands/managelogs"));
commands.set(managelogs_1.default.name, managelogs_1.default);
var message_1 = __importDefault(require("./commands/message"));
commands.set(message_1.default.name, message_1.default);
var ondisplaynamechange_1 = __importDefault(require("./commands/ondisplaynamechange"));
commands.set(ondisplaynamechange_1.default.name, ondisplaynamechange_1.default);
var onguildbanadd_1 = __importDefault(require("./commands/onguildbanadd"));
commands.set(onguildbanadd_1.default.name, onguildbanadd_1.default);
var onguildbanremove_1 = __importDefault(require("./commands/onguildbanremove"));
commands.set(onguildbanremove_1.default.name, onguildbanremove_1.default);
var onguilddelete_1 = __importDefault(require("./commands/onguilddelete"));
commands.set(onguilddelete_1.default.name, onguilddelete_1.default);
var onguildmemberadd_1 = __importDefault(require("./commands/onguildmemberadd"));
commands.set(onguildmemberadd_1.default.name, onguildmemberadd_1.default);
/*
import onguildmemberremove from './commands/onguildmemberremove';
commands.set(onguildmemberremove.name, onguildmemberremove);
import oninvitecreate from './commands/oninvitecreate';
commands.set(oninvitecreate.name, oninvitecreate);
import onmessagedelete from './commands/onmessagedelete';
commands.set(onmessagedelete.name, onmessagedelete);
import onmessagedeletebulk from './commands/onmessagedeletebulk';
commands.set(onmessagedeletebulk.name, onmessagedeletebulk);
import onmessagereactionadd from './commands/onmessagereactionadd';
commands.set(onmessagereactionadd.name, onmessagereactionadd);
import onmessageupdate from './commands/onmessageupdate';
commands.set(onmessageupdate.name, onmessageupdate);
import onnicknamechange from './commands/onnicknamechange';
commands.set(onnicknamechange.name, onnicknamechange);
import onroleaddorremove from './commands/onroleaddorremove';
commands.set(onroleaddorremove.name, onroleaddorremove);
import onrolecreate from './commands/onrolecreate';
commands.set(onrolecreate.name, onrolecreate);
import onroledelete from './commands/onroledelete';
commands.set(onroledelete.name, onroledelete);
import onusernamechange from './commands/onusernamechange';
commands.set(onusernamechange.name, onusernamechange);
import ping from './commands/ping';
commands.set(ping.name, ping);
import purge from './commands/purge';
commands.set(purge.name, purge);
import serverinfo from './commands/serverinfo';
commands.set(serverinfo.name, serverinfo);
import setbordercolor from './commands/setbordercolor';
commands.set(setbordercolor.name, setbordercolor);
import etdefaultrole from './commands/setdefaultrole';
commands.set(etdefaultrole.name, etdefaultrole);
import setdeletionstatus from './commands/setdeletionstatus';
commands.set(setdeletionstatus.name, setdeletionstatus);
import setreplacementinvite from './commands/setreplacementinvite';
commands.set(setreplacementinvite.name, setreplacementinvite);
import setverificationsystem from './commands/setverificationsystem';
commands.set(setverificationsystem.name, setverificationsystem);
import slashcommands from './commands/slashcommands';
commands.set(slashcommands.name, slashcommands);
import test from './commands/test';
commands.set(test.name, test);
import timedmessages from './commands/timedmessages';
commands.set(timedmessages.name, timedmessages);
import trackuser from './commands/trackuser';
commands.set(trackuser.name, trackuser);
import userinfo from './commands/userinfo';
commands.set(userinfo.name, userinfo);
*/
exports.default = { commands: commands };
