// CommandIndex.ts - Module for my commands index.
// Mar 24, 2021
// Chris M.
// https://github.com/RealTimeChris
'use strict';
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
var botCommands = new Map();
var botinfo_1 = __importDefault(require("./commands/botinfo"));
botCommands.set(botinfo_1.default.name, botinfo_1.default);
var deletedbentry_1 = __importDefault(require("./commands/deletedbentry"));
botCommands.set(deletedbentry_1.default.name, deletedbentry_1.default);
var displayguildsdata_1 = __importDefault(require("./commands/displayguildsdata"));
botCommands.set(displayguildsdata_1.default.name, displayguildsdata_1.default);
var ghost_1 = __importDefault(require("./commands/ghost"));
botCommands.set(ghost_1.default.name, ghost_1.default);
var help_1 = __importDefault(require("./commands/help"));
botCommands.set(help_1.default.name, help_1.default);
var jannyoptions_1 = __importDefault(require("./commands/jannyoptions"));
botCommands.set(jannyoptions_1.default.name, jannyoptions_1.default);
var listdbguilds_1 = __importDefault(require("./commands/listdbguilds"));
botCommands.set(listdbguilds_1.default.name, listdbguilds_1.default);
var managelogs_1 = __importDefault(require("./commands/managelogs"));
botCommands.set(managelogs_1.default.name, managelogs_1.default);
var message_1 = __importDefault(require("./commands/message"));
botCommands.set(message_1.default.name, message_1.default);
var ondisplaynamechange_1 = __importDefault(require("./commands/ondisplaynamechange"));
botCommands.set(ondisplaynamechange_1.default.name, ondisplaynamechange_1.default);
var onguildbanadd_1 = __importDefault(require("./commands/onguildbanadd"));
botCommands.set(onguildbanadd_1.default.name, onguildbanadd_1.default);
var onguildbanremove_1 = __importDefault(require("./commands/onguildbanremove"));
botCommands.set(onguildbanremove_1.default.name, onguildbanremove_1.default);
var onguilddelete_1 = __importDefault(require("./commands/onguilddelete"));
botCommands.set(onguilddelete_1.default.name, onguilddelete_1.default);
var onguildmemberadd_1 = __importDefault(require("./commands/onguildmemberadd"));
botCommands.set(onguildmemberadd_1.default.name, onguildmemberadd_1.default);
var onguildmemberremove_1 = __importDefault(require("./commands/onguildmemberremove"));
botCommands.set(onguildmemberremove_1.default.name, onguildmemberremove_1.default);
var oninvitecreate_1 = __importDefault(require("./commands/oninvitecreate"));
botCommands.set(oninvitecreate_1.default.name, oninvitecreate_1.default);
var onmessagedelete_1 = __importDefault(require("./commands/onmessagedelete"));
botCommands.set(onmessagedelete_1.default.name, onmessagedelete_1.default);
var onmessagedeletebulk_1 = __importDefault(require("./commands/onmessagedeletebulk"));
botCommands.set(onmessagedeletebulk_1.default.name, onmessagedeletebulk_1.default);
var onmessagereactionadd_1 = __importDefault(require("./commands/onmessagereactionadd"));
botCommands.set(onmessagereactionadd_1.default.name, onmessagereactionadd_1.default);
var onmessageupdate_1 = __importDefault(require("./commands/onmessageupdate"));
botCommands.set(onmessageupdate_1.default.name, onmessageupdate_1.default);
var onnicknamechange_1 = __importDefault(require("./commands/onnicknamechange"));
botCommands.set(onnicknamechange_1.default.name, onnicknamechange_1.default);
var onroleaddorremove_1 = __importDefault(require("./commands/onroleaddorremove"));
botCommands.set(onroleaddorremove_1.default.name, onroleaddorremove_1.default);
var onrolecreate_1 = __importDefault(require("./commands/onrolecreate"));
botCommands.set(onrolecreate_1.default.name, onrolecreate_1.default);
var onroledelete_1 = __importDefault(require("./commands/onroledelete"));
botCommands.set(onroledelete_1.default.name, onroledelete_1.default);
var onusernamechange_1 = __importDefault(require("./commands/onusernamechange"));
botCommands.set(onusernamechange_1.default.name, onusernamechange_1.default);
var ping_1 = __importDefault(require("./commands/ping"));
botCommands.set(ping_1.default.name, ping_1.default);
var purge_1 = __importDefault(require("./commands/purge"));
botCommands.set(purge_1.default.name, purge_1.default);
var serverinfo_1 = __importDefault(require("./commands/serverinfo"));
botCommands.set(serverinfo_1.default.name, serverinfo_1.default);
var setbordercolor_1 = __importDefault(require("./commands/setbordercolor"));
botCommands.set(setbordercolor_1.default.name, setbordercolor_1.default);
var setdefaultrole_1 = __importDefault(require("./commands/setdefaultrole"));
botCommands.set(setdefaultrole_1.default.name, setdefaultrole_1.default);
var setdeletionstatus_1 = __importDefault(require("./commands/setdeletionstatus"));
botCommands.set(setdeletionstatus_1.default.name, setdeletionstatus_1.default);
var setreplacementinvite_1 = __importDefault(require("./commands/setreplacementinvite"));
botCommands.set(setreplacementinvite_1.default.name, setreplacementinvite_1.default);
var setverificationsystem_1 = __importDefault(require("./commands/setverificationsystem"));
botCommands.set(setverificationsystem_1.default.name, setverificationsystem_1.default);
var slashcommands_1 = __importDefault(require("./commands/slashcommands"));
botCommands.set(slashcommands_1.default.name, slashcommands_1.default);
var test_1 = __importDefault(require("./commands/test"));
botCommands.set(test_1.default.name, test_1.default);
var timedmessages_1 = __importDefault(require("./commands/timedmessages"));
botCommands.set(timedmessages_1.default.name, timedmessages_1.default);
var trackuser_1 = __importDefault(require("./commands/trackuser"));
botCommands.set(trackuser_1.default.name, trackuser_1.default);
var userinfo_1 = __importDefault(require("./commands/userinfo"));
botCommands.set(userinfo_1.default.name, userinfo_1.default);
exports.default = botCommands;
