// commandindex.ts - Module for my commands index.
// Mar 24, 2021
// Chris M.
// https://github.com/RealTimeChris
'use strict';
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
var commands = new Map();
var botinfo_1 = __importDefault(require("./commands/botinfo"));
commands.set(botinfo_1.default.name, botinfo_1.default);
var deletedbentry_1 = __importDefault(require("./commands/deletedbentry"));
commands.set(deletedbentry_1.default.name, deletedbentry_1.default);
var displayguildsdata_1 = __importDefault(require("./commands/displayguildsdata"));
commands.set(displayguildsdata_1.default.name, displayguildsdata_1.default);
var ghost_1 = __importDefault(require("./commands/ghost"));
commands.set(ghost_1.default.name, ghost_1.default);
var help_1 = __importDefault(require("./commands/help"));
commands.set(help_1.default.name, help_1.default);
var jannyoptions_1 = __importDefault(require("./commands/jannyoptions"));
commands.set(jannyoptions_1.default.name, jannyoptions_1.default);
var listdbguilds_1 = __importDefault(require("./commands/listdbguilds"));
commands.set(listdbguilds_1.default.name, listdbguilds_1.default);
var managelogs_1 = __importDefault(require("./commands/managelogs"));
commands.set(managelogs_1.default.name, managelogs_1.default);
var message_1 = __importDefault(require("./commands/message"));
commands.set(message_1.default.name, message_1.default);
var ondisplaynamechange_1 = __importDefault(require("./commands/ondisplaynamechange"));
commands.set(ondisplaynamechange_1.default.name, ondisplaynamechange_1.default);
var onguildbanadd_1 = __importDefault(require("./commands/onguildbanadd"));
commands.set(onguildbanadd_1.default.name, onguildbanadd_1.default);
var onguildbanremove_1 = __importDefault(require("./commands/onguildbanremove"));
commands.set(onguildbanremove_1.default.name, onguildbanremove_1.default);
var onguilddelete_1 = __importDefault(require("./commands/onguilddelete"));
commands.set(onguilddelete_1.default.name, onguilddelete_1.default);
var onguildmemberadd_1 = __importDefault(require("./commands/onguildmemberadd"));
commands.set(onguildmemberadd_1.default.name, onguildmemberadd_1.default);
var onguildmemberremove_1 = __importDefault(require("./commands/onguildmemberremove"));
commands.set(onguildmemberremove_1.default.name, onguildmemberremove_1.default);
var oninvitecreate_1 = __importDefault(require("./commands/oninvitecreate"));
commands.set(oninvitecreate_1.default.name, oninvitecreate_1.default);
var onmessagedelete_1 = __importDefault(require("./commands/onmessagedelete"));
commands.set(onmessagedelete_1.default.name, onmessagedelete_1.default);
var onmessagedeletebulk_1 = __importDefault(require("./commands/onmessagedeletebulk"));
commands.set(onmessagedeletebulk_1.default.name, onmessagedeletebulk_1.default);
var onmessagereactionadd_1 = __importDefault(require("./commands/onmessagereactionadd"));
commands.set(onmessagereactionadd_1.default.name, onmessagereactionadd_1.default);
var onmessageupdate_1 = __importDefault(require("./commands/onmessageupdate"));
commands.set(onmessageupdate_1.default.name, onmessageupdate_1.default);
var onnicknamechange_1 = __importDefault(require("./commands/onnicknamechange"));
commands.set(onnicknamechange_1.default.name, onnicknamechange_1.default);
var onroleaddorremove_1 = __importDefault(require("./commands/onroleaddorremove"));
commands.set(onroleaddorremove_1.default.name, onroleaddorremove_1.default);
var onrolecreate_1 = __importDefault(require("./commands/onrolecreate"));
commands.set(onrolecreate_1.default.name, onrolecreate_1.default);
var onroledelete_1 = __importDefault(require("./commands/onroledelete"));
commands.set(onroledelete_1.default.name, onroledelete_1.default);
var onusernamechange_1 = __importDefault(require("./commands/onusernamechange"));
commands.set(onusernamechange_1.default.name, onusernamechange_1.default);
var ping_1 = __importDefault(require("./commands/ping"));
commands.set(ping_1.default.name, ping_1.default);
var purge_1 = __importDefault(require("./commands/purge"));
commands.set(purge_1.default.name, purge_1.default);
var serverinfo_1 = __importDefault(require("./commands/serverinfo"));
commands.set(serverinfo_1.default.name, serverinfo_1.default);
var setdefaultrole_1 = __importDefault(require("./commands/setdefaultrole"));
commands.set(setdefaultrole_1.default.name, setdefaultrole_1.default);
var setdeletionstatus_1 = __importDefault(require("./commands/setdeletionstatus"));
commands.set(setdeletionstatus_1.default.name, setdeletionstatus_1.default);
var setreplacementinvite_1 = __importDefault(require("./commands/setreplacementinvite"));
commands.set(setreplacementinvite_1.default.name, setreplacementinvite_1.default);
var setverificationsystem_1 = __importDefault(require("./commands/setverificationsystem"));
commands.set(setverificationsystem_1.default.name, setverificationsystem_1.default);
var test_1 = __importDefault(require("./commands/test"));
commands.set(test_1.default.name, test_1.default);
var timedmessages_1 = __importDefault(require("./commands/timedmessages"));
commands.set(timedmessages_1.default.name, timedmessages_1.default);
exports.default = { commands: commands };
